// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent that assesses loan eligibility based on user input.
 *
 * - assessLoanEligibility - A function that handles the loan eligibility assessment process.
 * - LoanEligibilityInput - The input type for the assessLoanEligibility function.
 * - LoanEligibilityOutput - The return type for the assessLoanEligibility function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const LoanEligibilityInputSchema = z.object({
  annualRevenue: z
    .number()
    .describe('The annual revenue of the business in USD.'),
  creditScore: z.number().describe('The credit score of the business owner.'),
  yearsInBusiness: z
    .number()
    .describe('The number of years the business has been in operation.'),
  loanAmountRequested: z
    .number()
    .describe('The amount of the loan requested in USD.'),
  reasonForLoan: z
    .string()
    .describe('The reason for requesting the loan.'),
});
export type LoanEligibilityInput = z.infer<typeof LoanEligibilityInputSchema>;

const LoanEligibilityOutputSchema = z.object({
  eligibilityStatus: z
    .string()
    .describe(
      'The eligibility status for the loan (e.g., Highly Eligible, Eligible, Low Eligibility, Ineligible).' + 
      'Also include suggestions to improve the eligibility for a loan if they are not Highly Eligible.'
    ),
  confidenceScore: z
    .number()
    .describe('A score between 0 and 1 indicating the confidence in the eligibility status.'),
});
export type LoanEligibilityOutput = z.infer<typeof LoanEligibilityOutputSchema>;

export async function assessLoanEligibility(
  input: LoanEligibilityInput
): Promise<LoanEligibilityOutput> {
  return assessLoanEligibilityFlow(input);
}

const prompt = ai.definePrompt({
  name: 'loanEligibilityPrompt',
  input: {schema: LoanEligibilityInputSchema},
  output: {schema: LoanEligibilityOutputSchema},
  prompt: `You are a loan eligibility assessment expert.

  Based on the following information, determine the eligibility status of the business for a loan.
  Provide a confidence score between 0 and 1 for your assessment.

  Annual Revenue: {{annualRevenue}} USD
  Credit Score: {{creditScore}}
  Years in Business: {{yearsInBusiness}}
  Loan Amount Requested: {{loanAmountRequested}} USD
  Reason for Loan: {{reasonForLoan}}

  Consider these factors when determining eligibility:
  - A higher annual revenue generally increases eligibility.
  - A higher credit score generally increases eligibility.
  - More years in business generally increases eligibility.
  - A lower loan amount requested compared to annual revenue increases eligibility.
  - The reason for the loan should be reasonable and contribute to business growth.

  Output the eligibility status and confidence score.
  If the eligibility status is not "Highly Eligible", provide suggestions to improve eligibility.
  `,
});

const assessLoanEligibilityFlow = ai.defineFlow(
  {
    name: 'assessLoanEligibilityFlow',
    inputSchema: LoanEligibilityInputSchema,
    outputSchema: LoanEligibilityOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
