
export type Testimonial = {
  name: string;
  location: string;
  quote: string;
  avatarUrl: string;
  rating: number;
};

export const testimonials: Testimonial[] = [
  {
    name: "Marie Dubois",
    location: "Paris, France",
    quote: "Le processus de prêt a été incroyablement simple et rapide. Capfinfy a vraiment compris mes besoins d'entrepreneur.",
    avatarUrl: "https://i.pravatar.cc/150?img=1",
    rating: 5,
  },
  {
    name: "Lukas Schmidt",
    location: "Berlin, Allemagne",
    quote: "J'ai pu financer mon nouvel équipement sans tracas. Leur équipe est professionnelle et très réactive. Je recommande vivement.",
    avatarUrl: "https://i.pravatar.cc/150?img=2",
    rating: 5,
  },
  {
    name: "Sofia Rossi",
    location: "Rome, Italie",
    quote: "Grâce à Capfinfy, j'ai consolidé mes dettes avec un rachat de crédit avantageux. Ma situation financière est bien meilleure maintenant.",
    avatarUrl: "https://i.pravatar.cc/150?img=3",
    rating: 4,
  },
  {
    name: "Liam O'Sullivan",
    location: "Dublin, Irlande",
    quote: "Obtenir un prêt immobilier semblait compliqué, mais ils ont simplifié chaque étape. Je suis maintenant propriétaire !",
    avatarUrl: "https://i.pravatar.cc/150?img=4",
    rating: 5,
  },
  {
    name: "Isabella Johansson",
    location: "Stockholm, Suède",
    quote: "Le prêt personnel m'a permis de réaliser le voyage de mes rêves. Service client exceptionnel et conditions claires.",
    avatarUrl: "https://i.pravatar.cc/150?img=5",
    rating: 5,
  },
  {
    name: "Carlos Garcia",
    location: "Madrid, Espagne",
    quote: "J'ai financé ma startup grâce à leur soutien. Une équipe qui croit vraiment aux projets innovants.",
    avatarUrl: "https://i.pravatar.cc/150?img=6",
    rating: 5,
  },
  {
    name: "Anna Petrova",
    location: "Varsovie, Pologne",
    quote: "Leur plateforme en ligne est très intuitive. J'ai soumis ma demande et obtenu une réponse en un temps record.",
    avatarUrl: "https://i.pravatar.cc/150?img=7",
    rating: 4,
  },
  {
    name: "David Nagy",
    location: "Budapest, Hongrie",
    quote: "Excellent service pour le financement de ma nouvelle voiture. Des taux compétitifs et aucune surprise.",
    avatarUrl: "https://i.pravatar.cc/150?img=8",
    rating: 5,
  },
  {
    name: "Elena Popescu",
    location: "Bucarest, Roumanie",
    quote: "J'ai apprécié la transparence et l'honnêteté de mon conseiller. On se sent en confiance.",
    avatarUrl: "https://i.pravatar.cc/150?img=9",
    rating: 5,
  },
  {
    name: "Nikos Papadopoulos",
    location: "Athènes, Grèce",
    quote: "Le rachat de mes crédits a été une bouffée d'air frais pour mon budget. Merci Capfinfy !",
    avatarUrl: "https://i.pravatar.cc/150?img=10",
    rating: 4,
  },
  {
    name: "Fatima Al-Sayed",
    location: "Lisbonne, Portugal",
    quote: "Ils m'ont aidée à financer des rénovations importantes dans ma maison. Je suis ravie du résultat.",
    avatarUrl: "https://i.pravatar.cc/150?img=11",
    rating: 5,
  },
  {
    name: "Jan Novak",
    location: "Prague, République Tchèque",
    quote: "En tant que freelance, obtenir un prêt est souvent difficile. Capfinfy a su analyser ma situation avec justesse.",
    avatarUrl: "https://i.pravatar.cc/150?img=12",
    rating: 5,
  },
  {
    name: "Freja Hansen",
    location: "Copenhague, Danemark",
    quote: "Simple, efficace et humain. Une expérience bancaire comme on en voit rarement.",
    avatarUrl: "https://i.pravatar.cc/150?img=13",
    rating: 5,
  },
  {
    name: "Lars Jansen",
    location: "Amsterdam, Pays-Bas",
    quote: "Le financement de ma flotte de véhicules d'entreprise a été géré de manière impeccable.",
    avatarUrl: "https://i.pravatar.cc/150?img=14",
    rating: 4,
  },
  {
    name: "Emilia Virtanen",
    location: "Helsinki, Finlande",
    quote: "Leur calculateur en ligne m'a donné une idée claire de mes options avant même de faire ma demande.",
    avatarUrl: "https://i.pravatar.cc/150?img=15",
    rating: 5,
  },
  {
    name: "Thomas Müller",
    location: "Vienne, Autriche",
    quote: "Le service client est remarquable. Ils répondent rapidement et avec précision à toutes les questions.",
    avatarUrl: "https://i.pravatar.cc/150?img=16",
    rating: 5,
  },
  {
    name: "Sophie Dubois",
    location: "Bruxelles, Belgique",
    quote: "J'ai obtenu un prêt étudiant pour mon master à l'étranger. Le processus était adapté à ma situation.",
    avatarUrl: "https://i.pravatar.cc/150?img=17",
    rating: 4,
  },
  {
    name: "Matej Horvat",
    location: "Zagreb, Croatie",
    quote: "Le rachat de crédit m'a permis de baisser mes mensualités de 30%. Je peux enfin respirer.",
    avatarUrl: "https://i.pravatar.cc/150?img=18",
    rating: 5,
  },
  {
    name: "Katarina Ivanov",
    location: "Belgrade, Serbie",
    quote: "Très satisfaite de mon prêt auto. J'ai pu acheter la voiture familiale dont nous avions besoin.",
    avatarUrl: "https://i.pravatar.cc/150?img=19",
    rating: 5,
  },
  {
    name: "Andrei Volkov",
    location: "Riga, Lettonie",
    quote: "Le financement pour l'expansion de mon magasin a été approuvé plus vite que je ne l'espérais.",
    avatarUrl: "https://i.pravatar.cc/150?img=20",
    rating: 5,
  },
  {
    name: "Ingrid Olsen",
    location: "Oslo, Norvège",
    quote: "Leur approche flexible pour les travailleurs indépendants est un vrai plus. Je les recommande.",
    avatarUrl: "https://i.pravatar.cc/150?img=21",
    rating: 4,
  },
  {
    name: "Viktor Orlov",
    location: "Sofia, Bulgarie",
    quote: "Un prêt personnel obtenu sans complications pour des travaux urgents dans ma maison.",
    avatarUrl: "https://i.pravatar.cc/150?img=22",
    rating: 5,
  },
  {
    name: "Zuzana Varga",
    location: "Bratislava, Slovaquie",
    quote: "Je suis passée par Capfinfy pour mon premier achat immobilier. Accompagnement parfait du début à la fin.",
    avatarUrl: "https://i.pravatar.cc/150?img=23",
    rating: 5,
  },
  {
    name: "Igor Kovalenko",
    location: "Kiev, Ukraine",
    quote: "J'ai été impressionné par leur capacité à trouver une solution de financement pour mon projet agricole.",
    avatarUrl: "https://i.pravatar.cc/150?img=24",
    rating: 4,
  },
  {
    name: "Sara Eriksson",
    location: "Göteborg, Suède",
    quote: "Le rachat de mes crédits étudiants m'a permis de mieux gérer mon budget mensuel. Service impeccable.",
    avatarUrl: "https://i.pravatar.cc/150?img=25",
    rating: 5,
  },
  {
    name: "Marco Conti",
    location: "Milan, Italie",
    quote: "Le financement de mon restaurant a été un succès grâce à leur expertise dans le secteur de la restauration.",
    avatarUrl: "https://i.pravatar.cc/150?img=26",
    rating: 5,
  },
  {
    name: "Eva Nowak",
    location: "Cracovie, Pologne",
    quote: "Le prêt m'a aidé à lancer ma boutique en ligne. Un vrai partenaire pour les petites entreprises.",
    avatarUrl: "https://i.pravatar.cc/150?img=27",
    rating: 5,
  },
  {
    name: "Daniel Fischer",
    location: "Hambourg, Allemagne",
    quote: "Service rapide et efficace pour le financement d'une voiture d'occasion. Je suis très satisfait.",
    avatarUrl: "https://i.pravatar.cc/150?img=28",
    rating: 4,
  },
  {
    name: "Clara Martins",
    location: "Porto, Portugal",
    quote: "Ils m'ont accompagné pour mon investissement locatif. Leurs conseils ont été précieux.",
    avatarUrl: "https://i.pravatar.cc/150?img=29",
    rating: 5,
  },
  {
    name: "Jean-Pierre Lambert",
    location: "Lyon, France",
    quote: "J'ai regroupé deux prêts personnels et un crédit auto. Ma gestion financière est maintenant bien plus simple.",
    avatarUrl: "https://i.pravatar.cc/150?img=30",
    rating: 5,
  },
];
